services:
  users-db:
    container_name: users-db
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users_service
    ports:
      - "5433:5432"
    networks:
      practicas_2026:
        aliases:
          - users-db
    volumes:
      - users_data:/var/lib/postgresql/data  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  users-service:
    container_name: users-service
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=docker
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=users-db
      - JWT_SECRET=tu_secreto_aqui
    ports:
      - "3400:3400"
    depends_on:
      users-db: 
        condition: service_healthy
    networks:
      practicas_2026:
        aliases:
          - users-service
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules

networks:
  practicas_2026:
    name: practicas_2026
    driver: bridge

volumes:
  users_data:   
